name = "tracethebreak-photos"
main = "index.js"
compatibility_date = "2024-09-23"

[[r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "report-photos"

[vars]
SUPABASE_URL = "https://fnkqmwweljsupbmerbkh.supabase.co"